const char * crazy_human_text =
"                                             ....',..........',;:cllllc:;;::cclloddxkkOO0KKXXXNNNNNNNNNNNWW\n"
"                                                ..;;.....   ...',;:codkkxdolloddxxkkOO00KKXXNNNNNWWWWWWWWWW\n"
"                               ..                  .;.        ..',;:codxkO00OkxxkkOO00KKXXNNNNWWWWWWWWWWWWW\n"
"                            ....                    ..        ...;c:;:lokO0KKXK0OOO00KKXXNNNWWWWWWWWWWWWWWW\n"
"                      .........                                 .'..',;:d0XKKXNNXKKKXXNNNWWWWWWWWMMMMMMMMMM\n"
"              .............''..                                   ....';:o0NNNNNNNNWWWWWWWMMMMMMMMMMMMMMMMM\n"
"        ..................''..                               ..     ...',:lkXWWWWWWWWWWMMMMMMMMMMMMMMMMMMMM\n"
"   ................'''',,,'..                                .'      ...',;lkKWWMMWWWMMMMMMMMMMMMMMMMMMMMMM\n"
"............'''',,,,;;;;:;..                                 ..        ...'cdkXWWMWWWMMMMMMMMMMMMMMMMMMMMMM\n"
"......''''',,,;;;;:::cllll;.          .;,.                              ...,ldONWWWWWMMMMMMMMMMMMMMMMMMMMMM\n"
"'''',,,,,;;;:::cclloddxkkOkd;.         ';,.                              ..,:okXWWWWWWMMMMMMMMMMMMMMMMMMMMM\n"
",,;;;;:::cccllodxkkO0KXXNNNNk...   ..   ..                                ..,cd0WWWWWWMMMMMMMMMMMMMMMMMMMWW\n"
"::clllooodxxkkO0KKXNNNNWWWWWk..'   ..                                      ..:dOXNWWWNWMMMMMMMMMMMMMMMWWWWW\n"
"lodxkkkOO0KKKXXXNNNWWWWWWWWWk.    .'.                                      .'codxk0XWWWMMMMMMMMMWWWWWWWWWWW\n"
"xkOO00KKXXNNNNNNNWWWWWWWWWWW0'   ..                                        .';:lc::lk0XWWWWWWWWWWWWWWWWWWWW\n"
"O00KKXXNNNNNNNWWWWWWWWWWWWWWXl..                                            ..,:;.. .:kXNWWWWWWWWWWWWWWWWWW\n"
"KKXXXNNNNNNNWWWWWWWWWWWWWNKd:.                                              .lKXXx,..lOKNWWWWWWWWWWWWWWWMMW\n"
"NNNNNNNNNNNWWWWWWWWWWWN0d:.                                                 .,loo:..,d0XNWWWWWWWMMMMMMMMMMM\n"
"NNNNNNNNNNWWWWWWWWWN0d;.         .,.                                     ..... ... ..cOKNMMMMMMMMMMMMMMMMMM\n"
"NNNNNNNNNNNWWWWWWNO:.          ;dKNk.                                    .col:,;:'...:dKWMMMMMMMMMMMMMMMMMM\n"
"NNNNNNNNNNNNNNKo:;.            ',;;;.                                     'okxll:;,:llo0MMMMMMMMMMMMMMMMMMM\n"
"NNXXXKKXXXXXN0:.                                                           'lkd:..,dKkxKMMMMMMMMMMMMMMMMMMM\n"
"NXXXK000000K0c.     .                                                       .,lc'.'cOOkXMMMMMMMMMMMMMMMMMMM\n"
"XXKK000OOOOkc.                         '.                                     .;cccokOOXMMMMMMMMMMMMMMMMMMM\n"
"K000OOOOOOx;.                 ,d;     .c;                                     ,cdl,cxo;cd0WMMMMMMMMMMMMMMMM\n"
"OOOOOOOOkl'.                  :o.                                             .,l:.;l'   .l0XWWWWMMMMMMMWWW\n"
"OOOOOOOx:..                                                                   .'::;c,      .';ldxkO0KXXNWWW\n"
"OOOOOko,..                 .                                                   .,lxl.  ..       ...,c;';lox\n"
"OOOOkl.....               ..                                                 .;ldKK;   .,.         ...     \n"
"0KKKo.....                                                                    .;:o;      ..   .....        \n"
"NNNNx. ...                                                                           .       ....,,.       \n"
"X0kd;                                                                                          ...         \n"
",.                                                                              ..                       ..\n";
